# Generated by Django 3.0 on 2022-08-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_student_student_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, choices=[('Unit_Test_1', 'Unit Test 1'), ('Unit_Test_2', 'Unit Test 2'), ('Unit_Test_3', 'Unit Test 3'), ('Unit_Test_4', 'Unit Test 4'), ('Semester1', 'Semester 1'), ('Semester2', 'Semester 2')], max_length=255, null=True)),
                ('test_class', models.CharField(blank=True, choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4')], max_length=255, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('no_que', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
