# Generated by Django 3.0 on 2022-08-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_student_course_name'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(blank=True, null=True)),
                ('course_ot', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AddTest')),
            ],
        ),
    ]
