# Generated by Django 3.0 on 2022-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignoutcome',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
