# Generated by Django 3.0 on 2022-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_student_course_name'),
        ('teacher', '0003_assignoutcome_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtain_mark', models.IntegerField(blank=True, null=True)),
                ('question_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AssignOutcome')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AddTest')),
            ],
        ),
    ]
