# Generated by Django 3.0 on 2022-08-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_cultural_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='sport_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
