# Generated by Django 3.0 on 2022-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_academiccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtest',
            name='test_class',
            field=models.CharField(blank=True, choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4'), ('5', 'Standard 5'), ('6', 'Standard 6'), ('7', 'Standard 7')], max_length=255, null=True),
        ),
    ]
