# Generated by Django 3.0 on 2022-08-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_schoolassignedteacher'),
        ('authapp', '0003_govtassignoutcome_govtsubject'),
        ('teacher', '0008_auto_20220825_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.GovtSubject'),
        ),
        migrations.CreateModel(
            name='SchoolAssignOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(blank=True, null=True)),
                ('course_ot', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('ques_info', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('subject_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AddTest')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAddTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, choices=[('Unit_Test_1', 'Unit Test 1'), ('Unit_Test_2', 'Unit Test 2'), ('Unit_Test_3', 'Unit Test 3'), ('Unit_Test_4', 'Unit Test 4'), ('Semester1', 'Semester 1'), ('Semester2', 'Semester 2')], max_length=255, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('no_que', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('subject_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
