# Generated by Django 3.0 on 2022-08-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20220825_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolassignoutcome',
            name='subject_info',
        ),
    ]
