# Generated by Django 3.0 on 2022-08-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_schoolassignedteacher'),
        ('teacher', '0011_auto_20220825_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class_subject'),
        ),
    ]
