# Generated by Django 3.0 on 2022-08-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20220825_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladdtest',
            name='no_que',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schooladdtest',
            name='total_marks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolassignoutcome',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
