# Generated by Django 3.0 on 2022-08-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20220825_2257'),
        ('teacher', '0016_auto_20220826_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmark',
            name='question_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.SchoolAssignOutcome'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class_subject'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.SchoolAddTest'),
        ),
    ]
