# Generated by Django 3.0 on 2022-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_auto_20220826_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmark',
            name='subject_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testmark',
            name='subject_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
