# Generated by Django 3.0 on 2022-07-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=255, null=True)),
                ('s_district', models.CharField(blank=True, max_length=255, null=True)),
                ('s_city', models.CharField(blank=True, max_length=255, null=True)),
                ('s_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(blank=True, max_length=255, null=True)),
                ('t_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('t_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_class', models.CharField(blank=True, max_length=255, null=True)),
                ('student_session', models.CharField(blank=True, max_length=255, null=True)),
                ('student_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('student_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class', models.CharField(blank=True, choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4')], max_length=255, null=True)),
                ('course_session', models.CharField(blank=True, max_length=255, null=True)),
                ('course_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
