# Generated by Django 3.0 on 2022-08-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
