# Generated by Django 3.0 on 2022-08-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_student_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_course_name',
        ),
    ]
