# Generated by Django 3.0 on 2022-08-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_student_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_subject',
            name='subject_name',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Maths', 'Maths'), ('Science', 'Science')], max_length=255, null=True),
        ),
    ]
