# Generated by Django 3.0 on 2022-07-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_class', models.IntegerField(blank=True, null=True)),
                ('course_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
