# Generated by Django 3.0 on 2022-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_assignedteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedteacher',
            name='course_class',
            field=models.IntegerField(blank=True, choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4')], null=True),
        ),
        migrations.AlterField(
            model_name='assignedteacher',
            name='course_name',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Maths', 'Maths')], max_length=255, null=True),
        ),
    ]
