# Generated by Django 3.0 on 2022-08-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20220817_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSportTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_class', models.CharField(blank=True, choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4')], max_length=255, null=True)),
                ('sport_session', models.CharField(blank=True, max_length=255, null=True)),
                ('sport_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('sport_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
