# Generated by Django 3.0 on 2022-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20220730_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedteacher',
            name='course_class',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
    ]
