# Generated by Django 3.0 on 2022-07-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20220730_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedteacher',
            name='course_class',
            field=models.CharField(blank=True, choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4')], max_length=255, null=True),
        ),
    ]
