# Generated by Django 3.0 on 2022-07-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20220730_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_course_name',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Maths', 'Maths')], max_length=255, null=True),
        ),
    ]
