# Generated by Django 3.0 on 2022-08-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_studentaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAccount',
        ),
    ]
