# Generated by Django 3.0 on 2022-07-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_student_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
