# Generated by Django 3.0 on 2022-08-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_studentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='COINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(blank=True, max_length=255, null=True)),
                ('co_info', models.CharField(blank=True, max_length=255, null=True)),
                ('co_class', models.CharField(blank=True, max_length=255, null=True)),
                ('co_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('co_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
