# Generated by Django 3.0 on 2022-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_coinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='reco',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
