# Generated by Django 3.0 on 2022-08-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_school_reco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='reco',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
