# Generated by Django 3.0 on 2022-08-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20220825_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='affi',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
