# Generated by Django 3.0 on 2022-08-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_govtassignoutcome_govtsubject'),
        ('school', '0014_auto_20220825_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_class_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.GovtSubject')),
                ('subject_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
    ]
