# Generated by Django 3.0 on 2022-08-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_school_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAssignedTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_session', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class_subject')),
                ('course_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
