# Generated by Django 3.0 on 2022-08-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_schoolassignedteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='affi',
        ),
        migrations.RemoveField(
            model_name='school',
            name='reco',
        ),
    ]
