# Generated by Django 3.0 on 2022-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20220825_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignsportteacher',
            name='sport_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
