# Generated by Django 3.0 on 2022-08-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_assignsportteacher_sport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignsportteacher',
            name='sport_type',
        ),
    ]
