# Generated by Django 3.0 on 2022-07-28 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_customuser_id_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=255, null=True)),
                ('s_district', models.CharField(blank=True, max_length=255, null=True)),
                ('s_city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='govt',
            new_name='is_govt',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='school',
            new_name='is_school',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='teacher',
            new_name='is_teacher',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(blank=True, max_length=255, null=True)),
                ('t_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_inventory_id', to='authapp.School')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='s_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
