# Generated by Django 3.0 on 2022-07-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20220729_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='t_school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
